"use client";

import * as React from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Ban, Check, ChevronLeft, ChevronRight, Edit3, Filter, Search, TrendingDown, TrendingUp, Wallet, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CapabilityNotice } from "@/components/feedback/capability-notice";
import { cn } from "@/lib/utils";
import type { FinanceEntryView, FinancePatientOption } from "@/types/finance";

const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
const unavailable = { key: "forecast-update", mode: "unavailable" as const, affectedAction: "mutate" as const, title: "Atualização financeira em preparação", message: "A previsão reflete dados reais de agenda. Confirmar, cancelar e editar lançamentos será liberado quando o serviço financeiro estiver conectado; nada foi alterado agora." };
function money(cents: number) { return (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function dateBR(value: string) { return new Intl.DateTimeFormat("pt-BR").format(new Date(value)); }
function isoDate(value: string) { const m = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(value); return m ? `${m[3]}-${m[2]}-${m[1]}` : ""; }
function brDate(value: string) { const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value); return m ? `${m[3]}/${m[2]}/${m[1]}` : value; }
function maskDate(value: string) { return value.replace(/\D/g, "").slice(0, 8).replace(/^(\d{2})(\d)/, "$1/$2").replace(/^(\d{2}\/\d{2})(\d)/, "$1/$2"); }

export function ForecastView({ entries }: { entries: FinanceEntryView[]; patients: FinancePatientOption[] }) {
  const search = useSearchParams(); const router = useRouter(); const pathname = usePathname();
  const now = new Date(); const year = Number(search.get("year")) || now.getFullYear(); const selectedMonth = search.get("month");
  const tab = search.get("tab") === "despesas" ? "despesas" : "receitas";
  const from = brDate(search.get("from") ?? ""); const to = brDate(search.get("to") ?? ""); const q = search.get("q") ?? ""; const category = search.get("category") ?? "todas";
  const patch = React.useCallback((values: Record<string, string | null>) => { const params = new URLSearchParams(search.toString()); Object.entries(values).forEach(([k, v]) => v ? params.set(k, v) : params.delete(k)); router.replace(`${pathname}?${params.toString()}`, { scroll: false }); }, [pathname, router, search]);
  const openMonth = (index: number, nextTab: "receitas" | "despesas") => { const key = `${year}-${String(index + 1).padStart(2, "0")}`; const last = new Date(year, index + 1, 0).getDate(); patch({ month: key, tab: nextTab, from: `${key}-01`, to: `${key}-${last}`, year: String(year) }); };
  const summaryFor = (index: number) => { const relevant = entries.filter((entry) => { const d = new Date(entry.date); return d.getFullYear() === year && d.getMonth() === index && entry.status !== "cancelado"; }); const receitaTotal = relevant.filter((x) => x.type === "receita").reduce((s, x) => s + x.valueCents, 0); const receitaEfetiva = relevant.filter((x) => x.type === "receita" && x.status === "efetivado").reduce((s, x) => s + x.valueCents, 0); const despesaTotal = relevant.filter((x) => x.type === "despesa").reduce((s, x) => s + x.valueCents, 0); const despesaEfetiva = relevant.filter((x) => x.type === "despesa" && x.status === "efetivado").reduce((s, x) => s + x.valueCents, 0); return { receitaTotal, receitaEfetiva, despesaTotal, despesaEfetiva, balance: receitaEfetiva - despesaEfetiva, predicted: receitaTotal - despesaTotal }; };
  if (!selectedMonth) return <div className="mx-auto max-w-[1360px] space-y-6 px-4 py-8 sm:px-6 lg:px-8"><header><h1 className="text-3xl font-bold">Previsibilidade financeira</h1><p className="mt-1 text-muted-foreground">Previstos, efetivados e confirmações por período</p></header><section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Calendário anual</h2><p className="text-sm text-muted-foreground">Clique em receitas ou despesas de um mês para ver os lançamentos.</p></div><div className="flex items-center gap-3"><Button variant="outline" size="icon" onClick={() => patch({ year: String(year - 1) })} aria-label="Ano anterior"><ChevronLeft className="size-4" /></Button><strong className="min-w-16 text-center text-lg">{year}</strong><Button variant="outline" size="icon" onClick={() => patch({ year: String(year + 1) })} aria-label="Próximo ano"><ChevronRight className="size-4" /></Button></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{months.map((label, index) => { const s = summaryFor(index); return <Card key={label} className="space-y-3 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{label}</h3><span className={cn("text-sm font-bold", s.balance >= 0 ? "text-primary" : "text-destructive")}>{money(s.balance)}</span></div><div className="grid grid-cols-2 gap-2"><MonthMetric label="Receitas" value={s.receitaTotal} tone="text-success" onClick={() => openMonth(index, "receitas")} /><MonthMetric label="Despesas" value={s.despesaTotal} tone="text-warning" onClick={() => openMonth(index, "despesas")} /></div><Mini label="Previsto" value={money(s.predicted)} /><Mini label="Efetivado" value={money(s.balance)} /></Card>; })}</div></section></div>;
  const [selectedYear, selectedIndex] = selectedMonth.split("-").map(Number); const start = from ? new Date(`${isoDate(from)}T00:00:00`) : new Date(selectedYear, selectedIndex - 1, 1); const end = to ? new Date(`${isoDate(to)}T23:59:59`) : new Date(selectedYear, selectedIndex, 0, 23, 59, 59); const selectedSummary = summaryFor(selectedIndex - 1);
  const filtered = entries.filter((entry) => { const d = new Date(entry.date); if (d < start || d > end) return false; if (tab === "receitas" && entry.type !== "receita") return false; if (tab === "despesas" && entry.type !== "despesa") return false; if (category !== "todas" && entry.category !== category) return false; return !q || `${entry.description} ${entry.patientName}`.toLowerCase().includes(q.toLowerCase()); });
  const pending = filtered.filter((entry) => entry.status === "previsto"); const effective = filtered.filter((entry) => entry.status === "efetivado");
  return <div className="mx-auto max-w-[1360px] space-y-4 px-4 py-8 sm:px-6 lg:px-8"><header><h1 className="text-3xl font-bold">Previsibilidade financeira</h1><p className="mt-1 text-muted-foreground">Previstos, efetivados e confirmações por período</p></header><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{months[selectedIndex - 1]} de {selectedYear}</h2><p className="text-sm text-muted-foreground">Resumo mensal com filtros por data, categoria e descrição.</p></div><Button variant="outline" onClick={() => patch({ month: null, from: null, to: null, tab: null })}><ChevronLeft className="size-4" /> Voltar</Button></div><div className="grid gap-3 md:grid-cols-3"><Summary label="Saldo final" value={selectedSummary.balance} sub="Previsto" subValue={selectedSummary.predicted} icon={Wallet} tone="text-primary" /><Summary label="Receitas do período" value={selectedSummary.receitaEfetiva} sub="Previsto" subValue={selectedSummary.receitaTotal} icon={TrendingUp} tone="text-success" /><Summary label="Despesas do período" value={selectedSummary.despesaEfetiva} sub="Previsto" subValue={selectedSummary.despesaTotal} icon={TrendingDown} tone="text-warning" /></div>
    <Card className="space-y-4 p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-muted-foreground"><Filter className="size-3.5" /> Filtros</span><button type="button" className="inline-flex items-center gap-1 text-xs" onClick={() => patch({ from: null, to: null, category: null, q: null })}><X className="size-3.5" /> Limpar filtros</button></div><div className="grid gap-3 lg:grid-cols-[150px_150px_180px_1fr]"><Field label="De"><Input inputMode="numeric" value={from} onChange={(e) => patch({ from: isoDate(maskDate(e.target.value)) || null })} /></Field><Field label="Até"><Input inputMode="numeric" value={to} onChange={(e) => patch({ to: isoDate(maskDate(e.target.value)) || null })} /></Field><Field label="Categoria"><Select value={category} onValueChange={(v) => patch({ category: v === "todas" ? null : v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todas">Todas</SelectItem><SelectItem value="Avulso">Avulso</SelectItem></SelectContent></Select></Field><Field label="Pesquisar"><div className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><Input className="pl-9" value={q} onChange={(e) => patch({ q: e.target.value || null })} placeholder="Buscar por nome ou descrição..." /></div></Field></div></Card>
    <Tabs value={tab} onValueChange={(v) => patch({ tab: v })}><TabsList><TabsTrigger value="receitas">Receitas</TabsTrigger><TabsTrigger value="despesas">Despesas</TabsTrigger></TabsList></Tabs><div className="grid gap-4 xl:grid-cols-2"><EntryBlock title="A confirmar" entries={pending} empty="Nenhum lançamento a confirmar." /><EntryBlock title="Efetivadas" entries={effective} empty="Nenhum lançamento efetivado." /></div>
  </div>;
}
function MonthMetric({ label, value, tone, onClick }: { label: string; value: number; tone: string; onClick: () => void }) { return <button type="button" className="rounded-lg border p-3 text-left transition-colors hover:bg-muted" onClick={onClick}><p className="text-[11px] uppercase text-muted-foreground">{label}</p><p className={cn("mt-1 text-lg font-bold", tone)}>{money(value)}</p></button>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between rounded-md bg-muted/60 px-2.5 py-2 text-xs"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>; }
function Summary({ label, value, sub, subValue, icon: Icon, tone }: { label: string; value: number; sub: string; subValue: number; icon: typeof Wallet; tone: string }) { return <Card className="flex items-start justify-between p-4"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className={cn("mt-1 text-2xl font-bold", tone)}>{money(value)}</p><div className="mt-3 border-t pt-2"><p className="text-[11px] uppercase text-muted-foreground">{sub}</p><p className="text-sm">{money(subValue)}</p></div></div><span className={cn("grid size-9 place-items-center rounded-lg bg-muted", tone)}><Icon className="size-4" /></span></Card>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="mb-1 block text-xs">{label}</Label>{children}</div>; }
function EntryBlock({ title, entries, empty }: { title: string; entries: FinanceEntryView[]; empty: string }) { return <Card className="p-4"><div className="flex items-end justify-between"><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-muted-foreground">{entries.length} lançamento(s)</p></div><strong>{money(entries.reduce((sum, entry) => sum + entry.valueCents, 0))}</strong></div>{entries.length ? <div className="mt-3 space-y-2">{entries.map((entry) => <div key={entry.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex items-center gap-2"><Badge tone={entry.status === "efetivado" ? "success" : "default"}>{entry.status === "efetivado" ? "Efetivado" : "Previsto"}</Badge><span className="text-xs text-muted-foreground">{dateBR(entry.date)}</span></div><p className="mt-2 font-medium">{entry.description}</p><p className="text-xs text-muted-foreground">{entry.patientName} · {entry.category}</p></div><p className="font-bold text-success">{money(entry.valueCents)}</p></div><div className="mt-2 flex justify-end gap-1"><CapabilityNotice descriptor={unavailable} trigger={<Button variant="ghost" size="icon" aria-label="Editar"><Edit3 className="size-4" /></Button>} /><CapabilityNotice descriptor={unavailable} trigger={<Button variant="ghost" size="icon" aria-label="Cancelar"><Ban className="size-4" /></Button>} />{entry.status === "previsto" ? <CapabilityNotice descriptor={unavailable} trigger={<Button size="icon" aria-label="Efetivar"><Check className="size-4" /></Button>} /> : null}</div></div>)}</div> : <div className="grid min-h-40 place-items-center text-sm text-muted-foreground">{empty}</div>}</Card>; }


